In [1]:
import pandas as pd

In [115]:
df = pd.read_json("untitled.json")

In [121]:
df.columns = pd.MultiIndex.from_tuples(s)

In [123]:
df

  تعداد دستورکارهای باز مربوط به تست 5                                       \
                            دردست اجرا تهیه صورت وضعیت صورت وضعیت نزد مشاور
0                                    0               0                    0
1                                   79               0                    0
2                                   79               1                   42
3                                    3               0                    0
4                                   32               0                    0

                                                                           \
  صورت وضعیت نزد ستاد صورت وضعیت نزد مالی مجموع دستورکارهای باز نیرورسانی
0                   0                   0                               0
1                   0                   0                              79
2                   5                   0                             127
3                   0                   0                               3
4                   0                   0                              32

  تعداد دستورکارهای باز مربوط به تست 1                                      \
                            دردست اجرا تهیه صورت وضعیت صورت وضعیت نزد ستاد
0                                    0               0                   0
1                                   17               0                   1
2                                    8               2                   3
3                                    1               0                   0
4                                    6               0                   3


  صورت وضعیت نزد مالی مجموع دستورکارهای باز بهره برداری
0                   0                                 0
1                   0                                18
2                   0                                13
3                   0                                 1
4                   0                                 9

In [119]:
for i in range(0,len(s)):
    s[i] = ast.literal_eval(s[i])

In [117]:
s = list(df.columns)

In [99]:
s.sort()

In [37]:
ast.literal_eval(s[0])

('تعداد دستورکارهای باز مربوط به تست 5', 'دردست اجرا')

In [71]:
s

[('تعداد دستورکارهای باز مربوط به تست 1', 'تهیه صورت وضعیت'),
 ('تعداد دستورکارهای باز مربوط به تست 1', 'دردست اجرا'),
 ('تعداد دستورکارهای باز مربوط به تست 1', 'صورت وضعیت نزد ستاد'),
 ('تعداد دستورکارهای باز مربوط به تست 1', 'صورت وضعیت نزد مالی'),
 ('تعداد دستورکارهای باز مربوط به تست 1', 'مجموع دستورکارهای باز بهره برداری'),
 ('تعداد دستورکارهای باز مربوط به تست 2', 'تهیه صورت وضعیت'),
 ('تعداد دستورکارهای باز مربوط به تست 2', 'دردست اجرا'),
 ('تعداد دستورکارهای باز مربوط به تست 2', 'صورت وضعیت نزد ستاد'),
 ('تعداد دستورکارهای باز مربوط به تست 2', 'صورت وضعیت نزد مالی'),
 ('تعداد دستورکارهای باز مربوط به تست 2',
  'مجموع دستورکارهای باز لوازم اندازه گیری'),
 ('تعداد دستورکارهای باز مربوط به تست 3', 'تهیه صورت وضعیت'),
 ('تعداد دستورکارهای باز مربوط به تست 3', 'دردست اجرا'),
 ('تعداد دستورکارهای باز مربوط به تست 3', 'صورت وضعیت نزد ستاد'),
 ('تعداد دستورکارهای باز مربوط به تست 3', 'صورت وضعیت نزد مالی'),
 ('تعداد دستورکارهای باز مربوط به تست 3',
  'مجموع دستورکارهای باز لوازم اندازه گیری'),
 ('تعداد دستورکارهای باز مربوط به تست 4', 'تهیه صورت وضعیت'),
 ('تعداد دستورکارهای باز مربوط به تست 4', 'دردست اجرا'),
 ('تعداد دستورکارهای باز مربوط به تست 4', 'صورت وضعیت نزد ستاد'),
 ('تعداد دستورکارهای باز مربوط به تست 4', 'صورت وضعیت نزد مالی'),
 ('تعداد دستورکارهای باز مربوط به تست 4', 'صورت وضعیت نزد مشاور'),
 ('تعداد دستورکارهای باز مربوط به تست 4', 'مجموع دستورکارهای باز سیم به کابل'),
 ('تعداد دستورکارهای باز مربوط به تست 5', 'تهیه صورت وضعیت'),
 ('تعداد دستورکارهای باز مربوط به تست 5', 'دردست اجرا'),
 ('تعداد دستورکارهای باز مربوط به تست 5', 'صورت وضعیت نزد ستاد'),
 ('تعداد دستورکارهای باز مربوط به تست 5', 'صورت وضعیت نزد مالی'),
 ('تعداد دستورکارهای باز مربوط به تست 5', 'صورت وضعیت نزد مشاور'),
 ('تعداد دستورکارهای باز مربوط به تست 5', 'مجموع دستورکارهای باز نیرورسانی'),
 ('تعداد دستورکارهای باز مربوط به تست 6', 'تهیه صورت وضعیت'),
 ('تعداد دستورکارهای باز مربوط به تست 6', 'دردست اجرا'),
 ('تعداد دستورکارهای باز مربوط به تست 6', 'صورت وضعیت نزد ستاد'),
 ('تعداد دستورکارهای باز مربوط به تست 6', 'صورت وضعیت نزد مالی'),
 ('تعداد دستورکارهای باز مربوط به تست 6', 'صورت وضعیت نزد مشاور'),
 ('تعداد دستورکارهای باز مربوط به تست 6', 'مجموع دستورکارهای باز تلفات'),
 ('تعداد دستورکارهای باز مربوط به تست 7', 'تهیه صورت وضعیت'),
 ('تعداد دستورکارهای باز مربوط به تست 7', 'دردست اجرا'),
 ('تعداد دستورکارهای باز مربوط به تست 7', 'صورت وضعیت نزد ستاد'),
 ('تعداد دستورکارهای باز مربوط به تست 7', 'صورت وضعیت نزد مالی'),
 ('تعداد دستورکارهای باز مربوط به تست 7', 'صورت وضعیت نزد مشاور'),
 ('تعداد دستورکارهای باز مربوط به تست 7',
  'مجموع دستورکارهای باز توسعه و احداث و اصلاح و روشنایی معابر و برگشتی و طرح جامع بم')]

In [1]:
import pandas as pd

In [9]:
import json
import pandas as pd
import ast  # امن‌تر از eval

with open("q.json", encoding="utf-8") as f:
    raw_str = json.load(f)  # این هنوز str هست
    data = json.loads(raw_str)  # حالا تبدیل به dict واقعی میشه

# حالا تبدیل کلیدها به tuple
data_fixed = {
    ast.literal_eval(k): v
    for k, v in data.items()
}

df = pd.DataFrame(data_fixed)
df.columns = pd.MultiIndex.from_tuples(df.columns)
df

   نام شهر   سال ماه تعداد دستورکارهای باز مربوط به تست 1                  \
                                               دردست اجرا تهیه صورت وضعیت
0    شهر 1  1401   7                                    0               0
1    شهر 2  1401   7                                   10               0
2    شهر 3  1401   7                                    6               0
3    شهر 4  1401   7                                   15               0
4    شهر 5  1401   7                                   34               0
5    شهر 6  1401   7                                    0               0
6    شهر 7  1401   7                                   17               0
7    شهر 8  1401   7                                   13               0
8    شهر 9  1401   7                                    8               2
9   شهر 10  1401   7                                   41               0
10  شهر 11  1401   7                                    6               0
11  شهر 12  1401   7                                    1               0
12  شهر 13  1401   7                                   17               0
13  شهر 14  1401   7                                   46               0
14  شهر 15  1401   7                                    7               0
15  شهر 16  1401   7                                    6               0
16   شهر 1  1401   8                                    0               0
17   شهر 2  1401   8                                   11               0
18   شهر 3  1401   8                                    5               0
19   شهر 4  1401   8                                   15               0
20   شهر 5  1401   8                                   20               0
21   شهر 6  1401   8                                    0               0
22   شهر 7  1401   8                                    7               0
23   شهر 8  1401   8                                   11               0
24   شهر 9  1401   8                                    8               2
25  شهر 10  1401   8                                   31               0
26  شهر 11  1401   8                                    1               0
27  شهر 12  1401   8                                    0               0
28  شهر 13  1401   8                                   10               0
29  شهر 14  1401   8                                   12               0
30  شهر 15  1401   8                                    7               0
31  شهر 16  1401   8                                    5               0
32   شهر 1  1401   9                                    0               0
33   شهر 2  1401   9                                   11               0
34   شهر 3  1401   9                                    2               0
35   شهر 4  1401   9                                    9               0
36   شهر 5  1401   9                                   19               0
37   شهر 6  1401   9                                    1               0
38   شهر 7  1401   9                                    7               0
39   شهر 8  1401   9                                    9               0
40   شهر 9  1401   9                                    4               0
41  شهر 10  1401   9                                   31               0
42  شهر 11  1401   9                                    1               0
43  شهر 12  1401   9                                    0               0
44  شهر 13  1401   9                                    6               0
45  شهر 14  1401   9                                   10               0
46  شهر 15  1401   9                                    3               0
47  شهر 16  1401   9                                    4               0


   صورت وضعیت نزد ستاد صورت وضعیت نزد مالی مجموع دستورکارهای باز بهره برداری
0                    0                   0                                 0
1                    0                   0                                10
2                    1                   0                                 7
3                    5                   0                                20
4                    1                   1                                36
5                    1                   0                                 1
6                    1                   0                                18
7                    1                   0                                14
8                    3                   0                                13
9                    1                   0                                42
10                   0                   0                                 6
11                   0                   0                                 1
12                   1                   0                                18
13                   0                   0                                46
14                   2                   0                                 9
15                   3                   0                                 9
16                   0                   0                                 0
17                   0                   0                                11
18                   1                   0                                 6
19                   1                   0                                16
20                   0                   1                                21
21                   1                   0                                 1
22                   0                   0                                 7
23                   1                   0                                12
24                   3                   0                                13
25                   0                   0                                31
26                   0                   0                                 1
27                   0                   0                                 0
28                   1                   0                                11
29                   0                   0                                12
30                   2                   0                                 9
31                   0                   0                                 5
32                   0                   0                                 0
33                   0                   0                                11
34                   1                   0                                 3
35                   1                   0                                10
36                   0                   1                                20
37                   0                   0                                 1
38                   0                   0                                 7
39                   1                   0                                10
40                   1                   0                                 5
41                   0                   0                                31
42                   0                   0                                 1
43                   0                   0                                 0
44                   1                   0                                 7
45                   0                   0                                10
46                   0                   0                                 3
47                   1                   0                                 5

In [11]:
df = pd.read_json("q.json" , orient="table")

ValueError: DataFrame constructor not properly called!